### ISSUE TITLE
struct run_config is too large

### ISSUE THREAD

**Issue by plavin** [hpcgarage/spatter#104]
I believe that struct run_config has gotten large with recent changes to the sizes of the statically allocated strings it holds. We should change any string that might be large to be dynamically allocated with asprintf. 

- [ ] Change strings in `struct run_config` to be dynamically allocated
- [ ] Remember to free those strings

**Comment by jyoung3131** [comment]
From #69  - If you use a really long index buffer, you can overflow a buffer that is used to pass data to the arg parse functionality.

Copying this data into a buffer was a hack to begin with, and we should see if we can avoid needing to do that copy. The error occurs on parse-args.c:169.

For now, I've increased STRING_SIZE. This seems to work alight as arrays of this size are mostly globals. However it is a waste of space, and not a real solution.

**Comment by jyoung3131** [comment]
From #69 If you use a really long index buffer, you can overflow a buffer that is used to pass data to the arg parse functionality.

Copying this data into a buffer was a hack to begin with, and we should see if we can avoid needing to do that copy. The error occurs on parse-args.c:169.

For now, I've increased STRING_SIZE. This seems to work alight as arrays of this size are mostly globals. However it is a waste of space, and not a real solution.

**Comment by plavin** [comment]
Addressed by #165
