### ISSUE TITLE
CMake Can't find Open MP on M2 mac

### ISSUE THREAD

**Issue by CHRISTIANDEROLF** [hpcgarage/spatter#110]
We added this to CMakeLists.txt
```
SET (TRGT spatter)
SET( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Xclang -fopenmp")
SET (OpenMP_C_FLAGS "-Xclang -fopenmp -I/opt/homebrew/Cellar/libomp/15.0.6/include -L/opt/homebrew/Cellar/libomp/15.0.6/lib")
SET (OpenMP_C_LIB_NAMES "libomp")
SET (OpenMP_libomp_LIBRARY "omp")
SET (OpenMP_CXX_FLAGS "-Xclang -fopenmp -I/opt/homebrew/Cellar/libomp/15.0.6/include -L/opt/homebrew/Cellar/libomp/15.0.6/lib")
SET (OpenMP_CXX_LIB_NAMES "libomp")
SET (LDFLAGS "${LDFLAGS} -L/opt/homebrew/Cellar/libomp/15.0.6/lib") 
```

**Comment by jyoung3131** [comment]
I think this may be fixed if we switch to using FindOpenMP https://cmake.org/cmake/help/v3.20/module/FindOpenMP.html, which has been on our roadmap. I'm going to tag this under our CMake improvements branch of things.

**Comment by agustin-vaca** [comment]
There have been reports of CMake not being able to find OpenMP on Mac. This issue has been noted on the README, and users are encouraged to use a Linux container, as implementing a solution for it can be overly hacky (installing OpenMP from source, which needs a full installation of XCode).
