### ISSUE TITLE
Rename "master" branch to "main" branch

### ISSUE THREAD

**Issue by plavin** [hpcgarage/spatter#116]
We should update to use the modern terminology for our main branch. I assume we can do this without breaking anything since we only ever push to feature branches. If there is anything to be careful about please comment.

**Comment by jyoung3131** [comment]
https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/

**Comment by JDTruj2018** [comment]
@jyoung3131 None that I am aware of. I'll make sure to have a fresh clone to be sure.

**Comment by jyoung3131** [comment]
Completed with and updated CI/CD workflow with d89f883
