### ISSUE TITLE
Improve CMakeLists Cross-Platform Compatibility for Compilers

### ISSUE THREAD

**Issue by jyoung3131** [hpcgarage/spatter#148]
Jered notes that we may want to avoid using the explicit calls to CMAKE_C_COMPILER since it conflicts with local default flags. 

https://stackoverflow.com/questions/45933732/how-to-specify-a-compiler-in-cmake

- We may want to avoid setting CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, and CMAKE_CUDA_COMPILER in CMakelists.txt
- If we do set CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, and CMAKE_CUDA_COMPILER in CMakelists.txt, we need to do so before any project statements.

**Comment by agustin-vaca** [comment]
Fixed by PR #145
