### ISSUE TITLE
Extraneous output

### ISSUE THREAD

**Issue by plavin** [hpcgarage/spatter#155]
https://github.com/hpcgarage/spatter/blob/8f6384a18e33cde6c1d9dbf0d8087f8bce0a694a/src/main.c#L1164

**Comment by JDTruj2018** [comment]
@plavin Go ahead and comment that one out or remove it. Looks like a printf I neglected to remove on commit that I had used for some testing.

**Comment by plavin** [comment]
Fixed in #156
