### ISSUE TITLE
Add CUDA API-based error checking to GPU kernels in CUDA backend

### ISSUE THREAD

**Issue by hagertnl** [hpcgarage/spatter#158]
CUDA kernels currently launch and complete without any form of checking utilizing the CUDA API. I might suggest that the following section of code be run after each kernel launch to check the status of the kernel launch. This performs a blocking operation until the kernel is finished, but that blocking is normally done by a cudaMemcpy anyway, so I don't believe this would impact the benchmark significantly. This could also be guarded by ifdef headers checking for `VALIDATE`, if it needs to be left out of production runs.
```
cudaError_t err = cudaPeekAtLastError();
if (err != cudaSuccess) printf("Kernel launch error!\n");
err = cudaDeviceSynchronize();
if (err != cudaSuccess) printf("Kernel run error!\n");
```
This would help address situations like #154 , but it would also catch errors such as compilation for incorrect GPU targets, maximum allowable thread count exceeded, device unable to be initialized, among other run-time errors that could occur on devices.

It may also be a good idea to check the return code on cudaMalloc and cudaMemcpy calls in `src/main.c`.

**Comment by jyoung3131** [comment]
Hi @hagertnl  - this should be fixed in our merging of a big refactor that @JDTruj2018 did including the CUDA backend.

Resolved in #165.
