### ISSUE TITLE
Option for atomics for Scatter with OpenMP and CUDA backends

### ISSUE THREAD

**Issue by JDTruj2018** [hpcgarage/spatter#178]
Add atomic operations for scatter kernels for the OpenMP and CUDA backends to prevent race conditions and properly order writes.

Should this be a command line option that can be toggled? Or just the default/only option?

**Comment by jyoung3131** [comment]
I am trying to think of a scenario where we would *not* want this to be the default, but maybe @plavin can also weigh in. 

My thought is that we would want this enabled by default unless we were explicitly trying to find issues with how a memory system orders writes at the HW level.
