### ISSUE TITLE
Memory Utilization

### ISSUE THREAD

**Issue by radelja** [hpcgarage/spatter#186]
There is an issue with the refactor using more memory than the current version. 

Using the uniform stride test ([cpu-ustride.json](https://github.com/hpcgarage/spatter/blob/main/standard-suite/basic-tests/cpu-ustride.json)) as an example, the Jupyter notebook mentions:

> This test will require 2GB of memory. The plots in the paper used 16 GB but we want this notebook to run quickly on laptops with less memory.

I ran the uniform stride test and confirmed the current version uses 1.9 GB of memory. When I ran the same test with the refactor, I found that it used 7.4 GB of memory.

However, the uniform stride test specifies UNIFORM patterns with NR and the refactor does not handle these patterns correctly. There are two branches that resolves the handling of these patterns:

https://github.com/radelja/spatter/tree/refactor-nr-fix
https://github.com/plavin/spatter/tree/refactor-new

Running the uniform stride test with either of these branches revealed the refactor uses 29.8 GB of memory compared to the 2 GB of memory used by the current version.

**Comment by jyoung3131** [comment]
Discussion noted that the refactor is using different buffers for each configuration, which is making the overall memory usage grow dramatically along with the runtime. 

There are two fixes we discussed:
1) Use the same buffers between configs which should make resize() operations much faster.
2) Incorporate the old Spatter function to calculate the max buffer size for vectors, and remove vector resize() operations.

**Comment by radelja** [comment]
I measured the memory usage of the current (main branch) and refactor ([refactor-new](https://github.com/plavin/spatter/tree/refactor-new) branch) versions of Spatter running [cpu-ustride.json](https://github.com/hpcgarage/spatter/blob/main/standard-suite/basic-tests/cpu-ustride.json) with the serial backend using valgrind's massif. The following graphs were generated with massif-visualizer:

Current
![main](https://github.com/hpcgarage/spatter/assets/89239568/3672af9f-52dc-4b3d-bf06-fcfc14b178a8)

Refactor
![refactor-new](https://github.com/hpcgarage/spatter/assets/89239568/bbd34749-5e11-42c2-807a-405e27355d7b)

**Comment by radelja** [comment]
Rerunning the above test with the changes from the [refactor-mem-fix](https://github.com/radelja/spatter/tree/refactor-mem-fix) branch produces the following graph:

Refactor
![refactor-changes](https://github.com/user-attachments/assets/ac246843-64f3-41d7-b635-d0dde3980fb8)

It now uses 1.9 GB of memory, just like the current version.

**Comment by radelja** [comment]
While this issue has been resolved for [cpu-ustride.json](https://github.com/hpcgarage/spatter/blob/main/standard-suite/basic-tests/cpu-ustride.json) and other trace files, there is still a memory usage issue with the [branson](https://github.com/hpcgarage/spatter-patterns/blob/main/ATS-5/Branson/main_marshak_wave_dd.json) trace. I ran the branson trace with the serial backend using massif on both the refactor and the original versions of Spatter. Here are the massif-visualizer graphs from these runs:

Original
![original_branson](https://github.com/user-attachments/assets/5dafa3e0-96bb-49eb-a583-9b5572a7b9a9)

Refactor
![branson](https://github.com/user-attachments/assets/e1215ca3-394d-4aaf-b1e8-018d6e58bf5f)

**Comment by radelja** [comment]
The [refactor-fix-args](https://github.com/radelja/spatter/tree/refactor-fix-args) branch resolves this issue for the [Branson](https://github.com/hpcgarage/spatter-patterns/blob/main/ATS-5/Branson/main_marshak_wave_dd.json) trace:

Refactor
![refactor-branson-new](https://github.com/user-attachments/assets/2e6d1e2d-e8fc-4cb7-991f-5d85e0f91151)

**Comment by radelja** [comment]
I ran [pennant_gpu.json](https://github.com/hpcgarage/spatter/blob/main/standard-suite/app-traces/pennant_gpu.json) with the CUDA backend on both the original and current versions of Spatter. The memory usage was measured with Massif and visualized with massif-visualizer:

Original
![pennant_gpu_v1](https://github.com/user-attachments/assets/01dfa532-51b4-4586-8db0-83f5eace25f1)

Current (previously referred to as Refactor)
![pennant_gpu_v2](https://github.com/user-attachments/assets/ba8c58b3-7dfe-4f2a-bc6a-b23cec63be36)
Note: this memory usage graph is incomplete, as an issue with Massif caused Spatter to terminate. This occurred after the buffers had already been allocated, so this graph should still show most of the memory usage.

The current version uses slightly more memory, but only for the CUDA backend. This issue seems to be resolved.

**Comment by jyoung3131** [comment]
Thanks for the detailed output, @radelja! I agree that this looks much improved with the refactor. I'll close this for now, and we can revisit if we see issues with these patterns or new ones we collect.
