### ISSUE TITLE
Deprecated -openmp flag for Intel compilers

### ISSUE THREAD

**Issue by ShadenSmith** [hpcgarage/spatter#2]
Hello!

The later Intel compilers have switched to the flag `-qopenmp` to enable OpenMP. You may want to instead use CMake's `find_package()` capability to be more flexible. Here is how I tackle that in [SPLATT](https://github.com/ShadenSmith/splatt):

```
  find_package(OpenMP)
  if(${OPENMP_FOUND})
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
  else()
    message("OpenMP runtime not found! SPLATT will not be multi-threaded.")
  endif()
```

**Comment by ShadenSmith** [comment]
Moreso, the configuration is limited to GOMP:
```
IF (USE_OPENMP)
    TARGET_LINK_LIBRARIES (spatter LINK_PUBLIC gomp)
ENDIF ()
```

The `find_package()` approach would avoid that complication too.

**Comment by avose** [comment]
The Cray compiler uses it's own OpenMP library by default, and if building normally (calling 'cc' -- the compiler wrapper script Cray uses), extra work should not be needed to link OpenMP.  That is, one should just use 'cc' and turn OpenMP on with one the supported flags, e.g., -- older CCE: 'cc -homp' (or on by default), cutting edge newer CCE versions may move to a more common 'cc -fopenmp' format.  But anyway, I'm just saying that one doesn't typically to anything else special at link time, as the 'cc' wrapper works with the 'modules' system to set all those flags up for the user automatically.  I do not know how this interacts with CMake, or if CMake knows anything about how to use Cray's OpenMP.

Now, there may be other design considerations for why you wouldn't want to do the following, but the ./configure/* files seem to be compiler and target specific anyway, with text in their names like "omp", "intel", etc.  Why not put the flags needed for OpenMP in there?  Then, when a user wants to target a new or a weird system like Cray, they can just put their flags in a new ./configure/* file?

**Comment by jyoung3131** [comment]
Hi Shaden - I merged your PR (thank you!) and am going to create a new issue to address the FindCuda/OCL libraries so we can test that separately. Closing this issue.
