### ISSUE TITLE
Add help option to parse-args

### ISSUE THREAD

**Issue by jyoung3131** [hpcgarage/spatter#20]
Currently we don't print out the possible options for using Spatter. We should add a default help function to print out all the possible Spatter options for those who don't use the scripts.

**Comment by jyoung3131** [comment]
#Patch from Jason as a starting point. 

diff --git a/src/parse-args.c b/src/parse-args.c
index ee81533..5f0b336 100644
--- a/src/parse-args.c
+++ b/src/parse-args.c
@@ -461,6 +461,8 @@ void parse_backend(int argc, char **argv)
     optind = 1;
         static struct option long_options[] =
     {
+        /* Politeness */
+        {"help", no_argument, NULL, 'h'},
         /* Output */
         {"no-print-header", no_argument,       NULL, 'q'},
         {"verbose",         no_argument,       &verbose, 1},
@@ -487,6 +489,10 @@ void parse_backend(int argc, char **argv)
                          long_options, &option_index);
 
         switch(c){
+            case 'h':
+                printf ("Wouldn't it be great to provide some 
help?\n");
+                exit (EXIT_SUCCESS);
+                break;
             case 'b':
                 if(!strcasecmp("OPENCL", optarg)){
                     backend = OPENCL;
--

**Comment by jyoung3131** [comment]
We could also make this more of an enhancement and use argtable to improve parsing overall.http://argtable.sourceforge.net/

**Comment by woodjamesdee** [comment]
Resolved by PR 49.
