### ISSUE TITLE
FPGA Static Report Generation Compiler Flags Issue

### ISSUE THREAD

**Issue by woodjamesdee** [hpcgarage/spatter#55]
clang++: warning: argument unused during compilation: '-Xshardware' [-Wunused-command-line-argument]   
[ 24%] Linking CXX executable spatter                                                                                                                                       clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/vpl/latest/lib' [-Wunused-command-line-argument]                        clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/oneDNN/2021.1-beta07/cpu_dpcpp_gpu_dpcpp/lib' [-Wunused-command-line-ar$ument]                                                                                                                                                                      clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/mpi/2021.1-beta07/libfabric/lib' [-Wunused-command-line-argument]       clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/mpi/2021.1-beta07/lib' [-Wunused-command-line-argument]                 clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/compiler/latest/linux/lib' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/usr/lib/gcc/x86_64-linux-gnu/7' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/tbb/2021.1-beta07/lib/intel64/gcc4.8' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/mpi/2021.1-beta07/lib/release' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/mkl/2021.1-beta07/lib/intel64' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/ipp/latest/lib/intel64' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/compiler/latest/linux/compiler/lib/intel64' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/tbb/latest/lib/intel64/gcc4.8' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/daal/latest/lib/intel64' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-L/net/tools/intel/oneapi/beta07/inteloneapi/clck/2021.1-beta07/lib/intel64' [-Wunused-command-line-argument]

**Comment by jyoung3131** [comment]
@woodjamesdee Can you add the command to recreate this bug?

**Comment by jyoung3131** [comment]
On discussion, it seems this was a tools version issue. Closing unless we see it again.
