### ISSUE TITLE
General documentation improvements

### ISSUE THREAD

**Issue by jyoung3131** [hpcgarage/spatter#77]
Update the documentation to make the following clearer:

1) Reading in trace inputs in LANL trace format.
2) How to build with different backends (ties in with Issue #60 and #28 )
3) How to run and interpret the 3 example test cases. 
4) Using related tools like dr-scatter-gather-trace with Spatter.

**Comment by plavin** [comment]
Add better explanations of GS, MultiScatter, and MultiGather kernels

**Comment by jyoung3131** [comment]
- [] Update the README to note the new flags and document what has changed.

**Comment by jyoung3131** [comment]
Closing this will also close #199
