### ISSUE TITLE
Segfault and Execution Tests

### ISSUE THREAD

**Issue by jyoung3131** [hpcgarage/spatter#81]
- [x] Add a test to see if output looks OK for CPU (ie, it runs and doesn't crash) and GPU with UNIFORM input
- [x] We use CTest to create tests and add them to "tests" folder. 
- [x] Test on flubber 3
- [x] Test GPU on quorra1/2

**Comment by jyoung3131** [comment]
- [ ] Test PR #73 on WSL and make sure UNIFORM runs correctly.

**Comment by plavin** [comment]
Segfaults should be fixed
