### ISSUE TITLE
Determine which plot tools are up-to-date and what should be culled

### ISSUE THREAD

**Issue by jyoung3131** [hpcgarage/spatter#82]
Our plots directory seems to be out-of-date. 

What would like to remove from the main repo?
- [x] Remove old R plot scripts

We'd like to add scripts to generate the following:
- [x] Figure 5 (general uniform stride plot)
- [x] Figure 9 (BW-BW plot)

**Comment by plavin** [comment]
Here is the directory with the plots used in the Memsys paper: 

https://github.com/hpcgarage/spatter_data/tree/master/results/v0.4/pattern_tests

**Comment by jyoung3131** [comment]
We'll delete the plots directory as none of the scripts are needed.

**Comment by jyoung3131** [comment]
The plotting scripts in PR #90 resolved the scripts requested here, and Jeff deleted the /plots folder from the main branch.
