### ISSUE TITLE
Spatter trace description for trace replay with architectural simulators

### ISSUE THREAD

**Issue by jyoung3131** [hpcgarage/spatter#89]
Some of this exists with SST's Miranda but we could make this its own module. We have recently compared Ariel trace replay with Spatter pattern generation.

- [ ] We'd like to have a module library that gets built as part of Spatter

**Comment by plavin** [comment]
This feature has been added as part of #165, and as a part of https://github.com/sstsimulator/sst-elements/pull/2348
